### ISSUE TITLE
Cognitohazardous Text

### ISSUE THREAD

**Issue by entropylost** [ZeroTixDev/Sase#1]
It has come to my attention that the text described in README.md is cognitohazardous, and I would appreciate it if you could remove the offending portion.

**Comment by 10maurycy10** [comment]
https://github.com/ZeroTixDev/Sase/pull/5

**Comment by 10maurycy10** [comment]
Try this https://github.com/ZeroTixDev/Sase/pull/6

**Comment by 10maurycy10** [comment]
This should be closed now.
